---
title: "01: Vectors (Solutions)"
author: "Charlie Lindgren"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Solutions

```{r, eval=TRUE, echo=TRUE}
# Solution to Exercise 1
my_numeric_vector <- c(10, 20, 30, 40, 50)
print(my_numeric_vector)

# Solution to Exercise 2
my_character_vector <- c("blue", "green", "purple")
print(my_character_vector)

# Solution to Exercise 3
length(my_numeric_vector)

# Solution to Exercise 4
mixed_vector <- c(1, TRUE, "hello")
print(mixed_vector)
# The vector is of type character due to coercion.

# Solution to Exercise 5
c(1, 2, 3) + c(4, 5, 6)

# Solution to Exercise 6
c(1, 2, 3) + c(4, 5)
# The shorter vector is recycled. A warning is issued.

# Solution to Exercise 7
my_results <- c()
my_results <- c(my_results, 10)
print(my_results)

# Solution to Exercise 8
my_vector <- c(1, 5, 2, 8, 4, NA)
sum(my_vector)
mean(my_vector)
prod(my_vector)
sum(my_vector, na.rm = TRUE)
mean(my_vector, na.rm = TRUE)
prod(my_vector, na.rm = TRUE)

# Solution to Exercise 9
my_vector <- c(1, 5, 2, 8, 4)
min(my_vector)
max(my_vector)

# Solution to Exercise 10
my_vector <- c(1, 5, 2, 8, 4)
sort(my_vector)
sort(my_vector, decreasing = TRUE)

# Solution to Exercise 11
5 %in% c(1, 5, 2, 8, 4)
```